language: node_js
node_js:
- "8.9.1"
deploy:
  provider: gae
  keyfile: anwesha-me-d2477c2dd62e.json
  project: anwesha-me
  config: app/app.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_fe3214124553_key -iv $encrypted_fe3214124553_iv
  -in anwesha-me-d2477c2dd62e.json.enc -out anwesha-me-d2477c2dd62e.json -d
script:
- node build
