deploy:
  provider: gae
  keyfile: anwesha-me-d2477c2dd62e.json
  project: valiant-song-187415
  config: app/app.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_05aa83e29456_key -iv $encrypted_05aa83e29456_iv
  -in anwesha-me-d2477c2dd62e.json.enc -out anwesha-me-d2477c2dd62e.json -d
